#cloud-config

packages:
  - build-essential
  - nginx

users:
  - name: nodecg
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']

runcmd:
  # Copy default dotfiles, which for some reason isn't done automatically?
  - cp -rT /etc/skel /home/nodecg
  # Disallow root login for security purposes. There should be no need to log in as root on a NodeCG box.
  - sed -i -e '/^PermitRootLogin/s/^.*$/PermitRootLogin no/' /etc/ssh/sshd_config
  # Silly hack to make `nvm` work from `su -c` commands
  - sed -i -e '/\*[)] return;;/s/^.*$/#      \*) return;;/' /home/nodecg/.bashrc
  # Explicitly permit the "nodecg" user to log in.
  - sed -i -e '$aAllowUsers nodecg' /etc/ssh/sshd_config
  # Restart SSH to apply the changes made to sshd_config
  - service sshd restart
  - chown -R nodecg:nodecg /home/nodecg/
  # Symlink the nginx site, overwriting the default symlink
  - ln -sf /etc/nginx/sites-available/nodecg /etc/nginx/sites-enabled/default
  # Install nvm, which we'll use to install the version of Node.js specified by nodejs_version in the deployment definition.
  - su - nodecg -c 'curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.0/install.sh | bash'
  # Prevent nvm from echoing "Now using..." when selecting a Node version.
  - 'sed -i -e ''/nvm_echo "$NVM_USE_OUTPUT"/s/^.*$/: #deliberate no-op by nodecg-cli/'' /home/nodecg/.nvm/nvm.sh'
  # pm2 startup
  # TODO: sudo env PATH=$PATH:/home/nodecg/.nvm/versions/node/v6.10.0/bin pm2 startup systemd -u nodecg --hp /home/nodecg
  #- su - nodecg -c 'env PATH=$PATH:/usr/bin pm2 startup systemd -u nodecg --hp /home/nodecg'
